@istest
public class testCustomerPortalController_oegen {
	static testMethod void tests(){
        
        TrialCustomerPortalHomePageController controller = new TrialCustomerPortalHomePageController();
        controller = new TrialCustomerPortalHomePageController(); 
        controller.SortProducts();
        controller.SortProducts();
        controller.SortCases();
        controller.SortSolutions();
        controller.SortIdeas();
	}
}