<p>
<b>Patch install:</b>
</p>
<p>
HRO IT Services will perform a patch install on the environment requested. This involves installing the update in both the application and database, propagating these changes to the web server, and then restoring any customisations. The environment will be offline for up to 30 minutes.
The patch install can only take place if the environments is at the correct major iTrent release version; eg. 10.19. Any patches or service packs required by the patch will also be installed.
Following the patch HRO IT Services will test connectivity to the environment; any other testing will be completed by the customer.
(Please Note: where approval is given to perform a change in Live this will be taken as confirmation that the customer has either performed UAT in a non-live environment or has deemed UAT not applicable and accepts the change directly into Live)</p>
