<p><b>Database Copy:</b>
</p>
<p>
HRO IT Services will perform a database copy. This involves replacing the destination database with a copy of the source database from a specific point in time in the 7 days prior to the time of the copy (by default the time the copy takes place). The destination environment will be offline for the duration of the copy - We advise around 3 hours however this will be dependent on your database size and content. The source environment is unaffected.
This copy can only take place if both environments are at the same major iTrent release version; eg. 10.19. If the source environment contains patches that the destination environment does not, these will be installed in the destination environment prior to the copy.
Following the copy HRO IT Services will test connectivity to the environment; any testing of the data is to be completed by the customer.</p>
